name: Deploy to Local

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # ← This makes it run on your machine
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy App
      run: |
        # Stop existing containers
        docker-compose down || true
        
        # Build and start fresh
        docker-compose up -d --build
        
        # Keep it running (don't stop)
        echo "🎉 App deployed! Access at: http://localhost"
