name: Simple CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and Test with Docker Compose
      run: |
        # Build and start all services (Flask + Nginx)
        docker-compose up -d --build
        
        # Wait for services to start
        sleep 10
        
        # Test if app is accessible through Nginx
        curl -f http://localhost:80/health
        
        # Test the main page
        curl -f http://localhost:80/
        
        # Stop everything
        docker-compose down
