name: Deploy to Local

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # ← This makes it run on your machine
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy App
      run: |
        # Stop existing containers
        docker-compose down
        
        # Build and start fresh
        docker-compose up -d --build

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-app:latest
        
        # Keep it running (don't stop)
        echo "🎉 App deployed! Access at: http://localhost"
